package pt.ulisboa.tecnico.hdsledger.utilities;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public abstract class Timestamp {
    private static final int secondWindow = 2 * 60; // two minutes
    private static final SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");

    public static String getCurrentTimestamp() {
        Date now = new Date();
        long time = now.getTime();
        return sdf.format(time);
    }

    public static boolean sameWindow(String timestamp1, String timestamp2) {
        // assumes timestamps were generated by getCurrentTimestamp
        if (timestamp1 == null || timestamp2 == null) {
            return false;
        }

        Date d1, d2;
        try {
            d1 = sdf.parse(timestamp1);
            d2 = sdf.parse(timestamp2);
        } catch (ParseException e) {
            e.printStackTrace();
            return false;
        }

        return Math.abs(d1.getTime() -d2.getTime()) <= secondWindow * 1000;
    }
}
