package pt.ulisboa.tecnico.hdsledger.utilities;

import java.text.SimpleDateFormat;
import java.util.Date;

public abstract class Timestamp {
    private static final int secondWindow = 2 * 60; // two minutes
    public static String getCurrentTimestamp() {
        // TODO(report): Messages that exceed the two-minute window are considered not fresh
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm");
        Date now = new Date();
        long time = now.getTime();
        long time2 = time - time % (secondWindow * 1000);
        now.setTime(time2);

        return sdf.format(now);
    }

    public static boolean sameWindow(String timestamp1, String timestamp2) {
        // assumes timestamps were generated by getCurrentTimestamp
        if (timestamp1 == null || timestamp2 == null) {
            return false;
        }
        return timestamp1.equals(timestamp2);
    }
}
